# Generated by Django 5.1.4 on 2025-03-12 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metadata', '0001_initial'),
        ('variables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('operator', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('chief_maneuver', models.CharField(max_length=30)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.departments')),
            ],
            options={
                'db_table': 'measurements',
            },
        ),
        migrations.CreateModel(
            name='ProfileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_descriptor', models.FloatField(default=0, null=True)),
                ('depth_marker', models.FloatField()),
                ('variable_value', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('quality_factor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='metadata.qualityfactors')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='variables.variables')),
            ],
            options={
                'verbose_name': 'ProfileData',
                'verbose_name_plural': 'ProfileDatas',
                'db_table': 'profile_data',
            },
        ),
    ]
