# Generated by Django 5.1.4 on 2025-03-12 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CecoldoCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'CecoldoCode',
                'verbose_name_plural': 'CecoldoCodes',
                'db_table': 'cecoldo_codes',
            },
        ),
        migrations.CreateModel(
            name='Coasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Coast',
                'verbose_name_plural': 'Coasts',
                'db_table': 'coasts',
            },
        ),
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Disciplines',
                'db_table': 'disciplines',
            },
        ),
        migrations.CreateModel(
            name='ProcessingLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=5)),
                ('level', models.SmallIntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'ProcessingLevel',
                'verbose_name_plural': 'ProcessingLevels',
                'db_table': 'processing_levels',
            },
        ),
        migrations.CreateModel(
            name='QualityFactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quality_flag', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'QualityFactor',
                'verbose_name_plural': 'QualityFactors',
                'db_table': 'quality_factors',
            },
        ),
        migrations.CreateModel(
            name='SamplingRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'SamplingRate',
                'verbose_name_plural': 'SamplingRates',
                'db_table': 'sampling_rates',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=5)),
                ('coast', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metadata.coasts')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='MeasurementUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=5)),
                ('symbol', models.CharField(max_length=20, null=True)),
                ('description', models.TextField(null=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metadata.disciplines')),
            ],
            options={
                'verbose_name': 'MeasurementUnit',
                'verbose_name_plural': 'MeasurementUnits',
                'db_table': 'measurement_units',
            },
        ),
    ]
