# Generated by Django 5.1.4 on 2025-03-12 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0001_initial'),
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='measurements.measurements'),
        ),
        migrations.AddField(
            model_name='maintenancesdates',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.equipments'),
        ),
        migrations.AddField(
            model_name='settings',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipments.equipments'),
        ),
    ]
