# Generated by Django 5.1.4 on 2025-03-12 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0001_initial'),
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=30)),
                ('align_ctd', models.FloatField(default=0)),
                ('description', models.TextField(null=True)),
                ('measurement_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.measurementunits')),
                ('processing_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metadata.processinglevels')),
                ('sampling_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metadata.samplingrates')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.equipments')),
            ],
            options={
                'verbose_name': 'Variable',
                'verbose_name_plural': 'Variables',
                'db_table': 'variables',
            },
        ),
    ]
